spring.application.name=supermarket

# Database Configuration (Microsoft SQL Server Express)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=lankafresh_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1234567
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Server Port
server.port=8081

# JWT Security Configurations
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
